### ISSUE TITLE
Complexity

### ISSUE THREAD

**Issue by zorkow** [mathjax/MathJax-RespEq#105] opened 2016-05-07 22:24 UTC
`data-semantic-complexity` can appear twice in MathML element. That leads to an XML error at my end.
I believe it only happens for mactions on the top level.
Example expression:

i = 1, 2, \ldots, n+1

**Comment by dpvc** [comment] 2016-05-14 23:00
I'm not able to reproduce this on the master branch.  Is it one of the other branches that causes this?  If not, is there something more that I'm supposed to do other than just enter the TeX expression above into the Semantics TeX lab?

**Comment by zorkow** [comment] 2016-05-17 10:15
This is what I get on master branch:
<mrow complexity="24" speech="i equals one comma two comma ellipsis comma n plus one" content="3,5,7" children="11,3,4,5,6,7,12" id="13" role="sequence" type="punctuated" complexity="24">

Uses 
MathJax.Ajax.config.path["SRE"] = "https://mathjax.github.io/MathJax-accessibility/dist";
and the above expression.

**Comment by dpvc** [comment] 2016-05-17 13:10
OK, I see it now.  Thanks!

**Comment by dpvc** [comment] 2016-05-17 15:22
I have submitted a pull request that fixes this issue.

**Comment by pkra** [comment] 2016-06-02 08:00
Fixed by #110.

**Closed by pkra** 2016-06-02 08:00 UTC
