### ISSUE TITLE
struik demo broken

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-RespEq#58] opened 2016-01-04 13:35 UTC
https://mathjax.github.io/MathJax-RespEq/Semantics-Lab/Struik.html gives me processing errors everywhere.

Maybe 2.6 related breakage?

**Comment by dpvc** [comment] 2016-01-04 13:52
Looks like the Struik page is badly out of date.  It still loads the InputHooks file that was removed some time ago, and (more importantly), calls on the old semantics.js rather than sre_mathJax.js.

I don't remember what functionality we wanted for that page.  Do you want the full walker, or just the responsive collapsing?

**Comment by dpvc** [comment] 2016-01-04 13:54
PS, the error message causing the problem is

    'undefined' is not an object (evaluating 'sre.Enrich.semanticMathmlSync')

so it is related to the semantic enrichment, and may be due to loading the wrong semantic enrichment file.

**Comment by dpvc** [comment] 2016-01-04 16:06
OK, I've added a `patch-struik` branch that fixes the call to `sre` that is causing the processing error.  This makes the page display, but it looks like the adaptive stuff isn't working.  I haven't looked into that yet.

**Comment by zorkow** [comment] 2016-01-05 22:06
I've fixed the patch to point to the correct library now (it's no longer semantics but enrich, the semantics library was still a left over.) 
There's still a timing issue, I could not fix or understand for that matter. Here's an attempt at an explanation:

If the initial rendering is finished before the MML.mbase.Augment functions are set, the enrichment does not have any effect.
Even if I call a rerender manually it is not used. So the jax.enriched actually contains the correctly enriched MathML expression, it is not used.

Currently this does not happen, since the enrich.js immediately sends a Sre Ready message, since speech is switched off and it assumes it is never used. But that's not ideal.

**Comment by dpvc** [comment] 2016-01-19 16:46
> There's still a timing issue, I could not fix or understand for that matter.

I've looked into it and think I know what is going on.  (More below)

> If the initial rendering is finished before the `MML.mbase.Augment` functions are set, the enrichment does not have any effect.  Even if I call a `rerender` manually it is not used.

You are correct about the timing of the `MML.mbase.Augment`.  The reason that `Rerender()` doesn't help is that the enrichment is done during the input phase, and `Rerender()` only redoes the output phase, not the input phase.  You would need to do `Reprocess()` to get both phases done.

Here's what's happening:  The Semantic-MathML extension waits for the "Sre Ready" signal before it modifies the mbase class, but although the `enrich.js` file is loaded first, it loads other auxiliary files asynchronously and (quite correctly) doesn't signal that it is ready until after that.  The problem is that the typesetting begins before Sre is fully set up, and so some math gets processed before the enrichment is available, so it doesn't collapse or do any of the other things associate with the enriched version.

The solution is to make MathJax wait with its typesetting until Sre is fully loaded.  The reason this isn't happening is that neither Semantic-MathML or enrich (or the other Semantic-* files) are proper extensions.  MathJax has synchronization code that prevents it from doing the typesetting until all the extensions are loaded, but since these aren't being loaded as true extensions, that code doesn't apply to them, and so the synchronization isn't working.

The easiest solution is probably to make these into true extensions.  The reason they weren't done that way originally was to make it easier to develop them, since extensions usually go in the MathJax/extensions folder, and we were keeping them separate in the RespEq repository.

At this point, it might be good to start treating them as actual extensions.  We should still be able to develop them here by setting a custom path (I'll work out the details) and adding them to the `extensions` array in the MathJax configuration.  That will make sure they are loaded before typesetting is complete.  I even think I can allow `enrich.js` to stay a separate file that isn't an extension and is loaded in the same way it currently is for now.

There are other ways that the synchronization could be handled, but they are more awkward.  It would be possible, for example, for `enrich.js` to actually cause MathJax to pause during the processing of the `"mml Jax Ready"` signal to which it ties its own ready signal.  Since typesetting won't continue until the mml ready signal, that would effectively pause typesetting until Sre is ready.  but it is a bit involved to do that.

Since Semantic-MathML can't be used outside of MathJax anyway, I think it is best to make it a true extension that MathJax will synchronize automatically.

**Comment by dpvc** [comment] 2016-01-19 16:48
If we are going to have external files like `enrich.js` that want to be able to cause MathJax to pause before typesetting that *aren't* going to be actual extensions, then we may want to develop an additional synchronization option.  E.g., a way to have these register with MathJax from the outside (rather than from the inside, like normal extensions), and signal when they are ready.  I have an outline of how that would work, so it might be worth adding it in.

**Comment by pkra** [comment] 2016-01-20 09:51
> I have an outline of how that would work, so it might be worth adding it in.

Sounds interesting. Let's discuss this at F2F today.

**Comment by dpvc** [comment] 2016-01-29 18:35
This should be taken care of by pull 61 (see above), so I'm closing it.

**Closed** 2016-01-29 18:35 UTC
